### ISSUE TITLE
Black text is hard to see on GitHub's dark mode

### ISSUE THREAD

**Issue by dylanmtaylor** [containers/.github#2]
![image](https://user-images.githubusercontent.com/277927/197886749-126984b7-8749-4eb2-be0e-1262027ae63e.png)

I'm not 100% sure how to fix this - maybe find a gray that looks good on both dark and light mode? This is primarily an issue w/ buildah and the container logo.

**Comment by rhatdan** [comment]
@mairin PTAL

**Comment by mairin** [comment]
Oh good spot. I have an idea on this - I can give them white circular bgs, would also help with the podman desktop alignment, I'm blocking off some time tomm to have a go at updating them.

**Comment by mairin** [comment]
@rhatdan feel free to assign to me (i don't seem to have ability to grab it)

**Comment by rhatdan** [comment]
It's yours.

**Comment by mairin** [comment]
![all-logos](https://user-images.githubusercontent.com/799683/200660014-b756fe7e-093f-4e4e-a39c-45800c9e40c1.png)

So this is my proposal, and it fixes two issues in one - aligning the logos across circular enclosures allows us to align the podman desktop logotype vertically and also gives us a way to provide a bg behind the logos so they're readable in dark mode. Putting together a PR for this now.

**Comment by mairin** [comment]
Ok, so this PR on the common repo adds the new logo files:
https://github.com/containers/common/pull/1228

Once that is accepted, I can change this PR on the README from draft to active status (it depends on those new image files being there):
https://github.com/containers/.github/pull/7
